
project_id = "sphere-mode"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions.statements-generator]
verify_jwt = true
