
project_id = "lqrbflaupbwizcyhwcsz"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.usp-canvas-ai]
verify_jwt = false

[functions.marketing-ai]
verify_jwt = false

[functions.process-document]
verify_jwt = true
