
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Strategy, Agent, AgentResult } from "@/types/marketing";
import { ArrowLeft, Play, RefreshCw, Save } from "lucide-react";

const StrategyDetails = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  
  const [strategy, setStrategy] = useState<Strategy | null>(null);
  const [loading, setLoading] = useState(true);
  const [runningAgent, setRunningAgent] = useState<string | null>(null);
  const [agentInput, setAgentInput] = useState<Record<string, string>>({});
  const [currentTab, setCurrentTab] = useState<string>('overview');

  useEffect(() => {
    if (!id) return;

    const fetchStrategy = async () => {
      try {
        // Fetch strategy details
        const { data: strategyData, error: strategyError } = await supabase
          .from('strategies')
          .select('*')
          .eq('id', id)
          .single();
        
        if (strategyError) throw strategyError;
        
        // Fetch agents for this strategy
        const { data: agentsData, error: agentsError } = await supabase
          .from('agents')
          .select('*')
          .eq('strategy_id', id);
        
        if (agentsError) throw agentsError;
        
        // Fetch results for this strategy
        const { data: resultsData, error: resultsError } = await supabase
          .from('agent_results')
          .select('*')
          .eq('strategy_id', id);
        
        if (resultsError) throw resultsError;
        
        // Transform the data to match our interfaces
        const transformedAgents: Agent[] = agentsData?.map((agent) => ({
          id: agent.id,
          name: agent.name,
          type: agent.type,
          description: agent.description || '',
          isActive: agent.is_active
        })) || [];

        const transformedResults: AgentResult[] = resultsData?.map((result) => ({
          id: result.id,
          agentId: result.agent_id || '',
          strategyId: result.strategy_id || '',
          content: result.content,
          createdAt: result.created_at,
          metadata: result.metadata || {}
        })) || [];

        // Combine all data
        setStrategy({
          id: strategyData.id,
          name: strategyData.name,
          description: strategyData.description || '',
          status: strategyData.status,
          createdAt: strategyData.created_at,
          updatedAt: strategyData.updated_at,
          agents: transformedAgents,
          results: transformedResults
        });

        // Initialize agent input state
        const initialInputs: Record<string, string> = {};
        transformedAgents.forEach((agent) => {
          initialInputs[agent.id] = '';
        });
        setAgentInput(initialInputs);
        
        // Set the first agent as the current tab if available
        if (transformedAgents && transformedAgents.length > 0) {
          setCurrentTab(transformedAgents[0].id);
        }
      } catch (error) {
        console.error('Error fetching strategy:', error);
        toast({
          title: "Error",
          description: "Failed to load strategy details",
          variant: "destructive",
        });
      } finally {
        setLoading(false);
      }
    };

    fetchStrategy();
  }, [id, toast]);

  const runAgent = async (agentId: string) => {
    if (!strategy) return;
    
    const agent = strategy.agents.find(a => a.id === agentId);
    if (!agent) return;
    
    setRunningAgent(agentId);
    
    try {
      // This is where you would call your backend function to run the agent
      // For now, we'll simulate a response
      const simulatedResult = `Sample output for ${agent.name}.\n\nThis is a placeholder for the actual agent output. In a real application, this would be generated by calling a backend function that runs the specific agent with the provided input and context from other agents' results.`;
      
      // Save the result to the database
      const { data, error } = await supabase
        .from('agent_results')
        .insert({
          agent_id: agentId,
          strategy_id: strategy.id,
          content: simulatedResult,
          created_at: new Date().toISOString(),
          metadata: { input: agentInput[agentId] }
        })
        .select('*')
        .single();
      
      if (error) throw error;
      
      // Transform the new result to match our interface
      const newResult: AgentResult = {
        id: data.id,
        agentId: data.agent_id || '',
        strategyId: data.strategy_id || '',
        content: data.content,
        createdAt: data.created_at,
        metadata: data.metadata || {}
      };
      
      // Update the strategy state with the new result
      setStrategy(prev => {
        if (!prev) return null;
        return {
          ...prev,
          results: [...prev.results, newResult]
        };
      });
      
      toast({
        title: "Success",
        description: `${agent.name} completed successfully!`,
      });
    } catch (error) {
      console.error('Error running agent:', error);
      toast({
        title: "Error",
        description: `Failed to run ${agent.name}`,
        variant: "destructive",
      });
    } finally {
      setRunningAgent(null);
    }
  };

  const getAgentResult = (agentId: string) => {
    if (!strategy) return null;
    return strategy.results.find(r => r.agentId === agentId);
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-start">
          <Button variant="ghost" onClick={() => navigate(-1)} className="mb-6">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back
          </Button>
        </div>
        <div className="h-[600px] flex items-center justify-center">
          <RefreshCw className="h-8 w-8 animate-spin" />
        </div>
      </div>
    );
  }

  if (!strategy) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-start">
          <Button variant="ghost" onClick={() => navigate(-1)} className="mb-6">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back
          </Button>
        </div>
        <Card className="w-full">
          <CardContent className="p-6 flex flex-col items-center justify-center h-[400px]">
            <p className="text-xl text-gray-500">Strategy not found</p>
            <Button onClick={() => navigate('/dashboard')} className="mt-4">
              Back to Dashboard
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex justify-start">
        <Button variant="ghost" onClick={() => navigate(-1)} className="mb-6">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>
      </div>
      
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold">{strategy.name}</h1>
          <p className="text-gray-500 mt-1">{strategy.description}</p>
        </div>
        <div className="mt-4 md:mt-0">
          <span className={`px-3 py-1 rounded-full text-sm font-medium
            ${strategy.status === 'completed' ? 'bg-green-100 text-green-800' : 
              strategy.status === 'in_progress' ? 'bg-blue-100 text-blue-800' :
              'bg-gray-100 text-gray-800'}`}>
            {strategy.status.replace('_', ' ').toUpperCase()}
          </span>
        </div>
      </div>

      <Tabs value={currentTab} onValueChange={setCurrentTab} className="w-full">
        <TabsList className="w-full overflow-x-auto flex whitespace-nowrap">
          <TabsTrigger value="overview">Strategy Overview</TabsTrigger>
          {strategy.agents.map(agent => (
            <TabsTrigger key={agent.id} value={agent.id}>
              {agent.name}
            </TabsTrigger>
          ))}
        </TabsList>
        
        <TabsContent value="overview" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>Strategy Overview</CardTitle>
              <CardDescription>
                Combined results from all marketing agents
              </CardDescription>
            </CardHeader>
            <CardContent>
              {strategy.results.length > 0 ? (
                <div className="space-y-8">
                  {strategy.agents.map(agent => {
                    const result = getAgentResult(agent.id);
                    return result ? (
                      <div key={agent.id} className="border-b pb-6 last:border-b-0 last:pb-0">
                        <h3 className="text-lg font-medium mb-2">{agent.name}</h3>
                        <div className="whitespace-pre-wrap bg-muted p-4 rounded-md">
                          {result.content}
                        </div>
                      </div>
                    ) : null;
                  })}
                </div>
              ) : (
                <div className="text-center py-8">
                  <p className="text-gray-500 mb-4">
                    No results yet. Run agents to generate marketing insights.
                  </p>
                  <Button onClick={() => setCurrentTab(strategy.agents[0]?.id)}>
                    Start with First Agent
                  </Button>
                </div>
              )}
            </CardContent>
            <CardFooter>
              <Button
                variant="outline"
                onClick={() => {
                  // Here you would export the full strategy results
                  toast({
                    title: "Feature Coming Soon",
                    description: "Export functionality will be available soon"
                  });
                }}
              >
                Export Results
              </Button>
            </CardFooter>
          </Card>
        </TabsContent>
        
        {strategy.agents.map(agent => {
          const result = getAgentResult(agent.id);
          return (
            <TabsContent key={agent.id} value={agent.id} className="mt-6">
              <Card>
                <CardHeader>
                  <CardTitle>{agent.name}</CardTitle>
                  <CardDescription>{agent.description}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <h3 className="text-sm font-medium">Agent Input</h3>
                    <Textarea 
                      placeholder={`Enter instructions for ${agent.name}...`}
                      value={agentInput[agent.id] || ''}
                      onChange={(e) => setAgentInput({...agentInput, [agent.id]: e.target.value})}
                      className="min-h-[100px]"
                    />
                    <p className="text-xs text-gray-500">
                      Provide specific instructions for this agent. You can reference other agent results.
                    </p>
                  </div>
                  
                  {result && (
                    <div className="space-y-2">
                      <h3 className="text-sm font-medium">Agent Result</h3>
                      <div className="whitespace-pre-wrap bg-muted p-4 rounded-md min-h-[200px]">
                        {result.content}
                      </div>
                      <p className="text-xs text-gray-500">
                        Generated on {new Date(result.createdAt).toLocaleString()}
                      </p>
                    </div>
                  )}
                </CardContent>
                <CardFooter className="flex justify-between">
                  <Button
                    variant="outline"
                    onClick={() => navigate('/dashboard')}
                  >
                    Back to Dashboard
                  </Button>
                  <Button 
                    onClick={() => runAgent(agent.id)}
                    disabled={runningAgent !== null}
                  >
                    {runningAgent === agent.id ? (
                      <>
                        <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        Running...
                      </>
                    ) : (
                      <>
                        <Play className="mr-2 h-4 w-4" />
                        {result ? "Re-run Agent" : "Run Agent"}
                      </>
                    )}
                  </Button>
                </CardFooter>
              </Card>
            </TabsContent>
          );
        })}
      </Tabs>
    </div>
  );
};

export default StrategyDetails;
