
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqrbflaupbwizcyhwcsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcmJmbGF1cGJ3aXpjeWh3Y3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzI1OTIsImV4cCI6MjA2MTE0ODU5Mn0.litCu9gZUJ8xAnZXWmsEMxxsJigPQT5YqNMZ0vf6oMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
